Default: &defaults
  database: ajaxserver.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ajaxserver_test.sqlite3
  <<: *defaults

Staging:
  database: ajaxserver_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ajaxserver_production.sqlite3
  poolsize: 100
  <<: *defaults
